# Generated by Django 5.1.7 on 2025-04-25 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PiezaMusical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Título no disponible', max_length=255)),
                ('compositor', models.CharField(default='Compositor desconocido', max_length=100)),
                ('fecha_composicion', models.CharField(blank=True, max_length=50, null=True)),
                ('derechos', models.CharField(blank=True, default='Dominio público', max_length=100, null=True)),
                ('partitura_musicxml', models.FileField(upload_to='partituras/musicxml/')),
                ('analisis_data', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametros', models.JSONField(default=dict)),
                ('archivo_musicxml', models.FileField(upload_to='ejercicios/musicxml/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('partitura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='repertorio.piezamusical')),
            ],
            options={
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['partitura', 'creado_en'], name='repertorio__partitu_82d4ce_idx')],
            },
        ),
    ]
