# Generated by Django 5.2.4 on 2025-07-20 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('escalas', 'Escalas Tonales'), ('saltos', 'Técnica de Saltos'), ('ritmos', 'Coordinación Rítmica'), ('acordes', 'Progresiones Armónicas')], max_length=20)),
                ('parametros', models.JSONField(default=dict)),
                ('archivo_musicxml', models.FileField(upload_to='ejercicios/musicxml/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PiezaMusical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Título no disponible', max_length=255)),
                ('compositor', models.CharField(default='Compositor desconocido', max_length=100)),
                ('fecha_composicion', models.CharField(blank=True, max_length=50, null=True)),
                ('derechos', models.CharField(blank=True, default='Dominio público', max_length=100, null=True)),
                ('partitura_musicxml', models.FileField(upload_to='partituras/musicxml/')),
                ('analisis_data', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('tipo', models.CharField(choices=[('OBSERVACION', 'Observación técnica'), ('RECORDATORIO', 'Recordatorio'), ('ANALISIS', 'Análisis musical'), ('EJERCICIO', 'Ejercicio relacionado')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ejercicio_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_tecnicas', to='repertorio.ejercicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pieza_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_tecnicas', to='repertorio.piezamusical')),
            ],
            options={
                'verbose_name': 'Nota Técnica',
                'verbose_name_plural': 'Notas Técnicas',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='partitura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='repertorio.piezamusical'),
        ),
        migrations.CreateModel(
            name='DominioPieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('PR', 'Principiante'), ('IN', 'Intermedio'), ('AV', 'Avanzado'), ('PR', 'Profesional')], default='PR', max_length=2)),
                ('ultima_practica', models.DateField(blank=True, null=True)),
                ('grabacion_original', models.FileField(blank=True, null=True, upload_to='grabaciones/originales/')),
                ('grabacion_ejecucion', models.FileField(blank=True, null=True, upload_to='grabaciones/ejecuciones/')),
                ('progreso', models.IntegerField(default=0)),
                ('pieza', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dominio', to='repertorio.piezamusical')),
            ],
            options={
                'verbose_name': 'Dominio de Pieza',
                'verbose_name_plural': 'Dominios de Piezas',
            },
        ),
    ]
